- name: install qemu guest agent on vm
  hosts: all
  tasks:
    - name: update apt cache
      command: apt update 

    - name: install qemu guest agent
      command: apt -y install qemu-guest-agent

    - name: enable agent
      command: systemctl enable qemu-guest-agent
    
    - name: start agent
      command: systemctl start qemu-guest-agent
 