- name: install qemu guest agent on vm
  hosts: all
  tasks:
   - name: Ping my hosts
     ansible.builtin.ping:

   - name: Print message
     ansible.builtin.debug:
      msg: Hello world


# - name: install qemu guest agent on vm
#   host: all
#   gather_facts: false
#   become: yes

#   tasks:
#     - name: update apt cache
#       command: apt update 

#     - name: install quemu guest agent
#       command: apt -y install qemu-guest-agent

#     - name: enable agent
#       command: systemctl enable qemu-guest-agent
      
#     - name: start agent
#       command: systemctl start qemu-guest-agent